# Generated by Django 4.1.5 on 2023-03-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_brand_car_brand'),
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='cdw',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExtraReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_reserves', to='home.extras')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_reserves', to='reserve.reserve')),
            ],
        ),
    ]
