# Generated by Django 4.1.5 on 2023-03-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reserve_cdw_extrareserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='full_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pending_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pickup_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='rent_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='return_place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='to_be_paid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserve',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
