# Generated by Django 4.1.5 on 2023-06-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_reserve_discount_reserve_full_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrareserve',
            name='later_pay_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='extrareserve',
            name='now_pay_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='extrareserve',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
