# Generated by Django 4.1.5 on 2023-06-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_extrareserve_later_pay_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrareserve',
            name='later_pay_cost',
        ),
        migrations.RemoveField(
            model_name='extrareserve',
            name='now_pay_cost',
        ),
        migrations.RemoveField(
            model_name='extrareserve',
            name='total_cost',
        ),
    ]
