# Generated by Django 4.1.5 on 2023-01-29 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='total_price',
        ),
    ]
