# Generated by Django 4.1.5 on 2023-01-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_car_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='amount',
        ),
    ]
