# Generated by Django 4.1.5 on 2023-01-29 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_car_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='engine',
            new_name='engine_petrol',
        ),
    ]
