# Generated by Django 4.1.5 on 2023-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_engine_car_engine_petrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
