# Generated by Django 4.1.5 on 2023-01-31 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_category_sub_cat_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
    ]
