# Generated by Django 4.1.5 on 2023-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_features_delete_carfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, null=True, related_name='features', to='home.carfeatures')),
            ],
        ),
    ]
