# Generated by Django 4.1.5 on 2023-01-31 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_carfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfeatures',
            name='car_features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='home.features'),
        ),
    ]
