# Generated by Django 4.1.5 on 2023-01-31 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_car_features_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.features'),
        ),
    ]
