# Generated by Django 4.1.5 on 2023-01-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_car_features_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, null=True, related_name='features', to='home.features'),
        ),
    ]
