# Generated by Django 4.1.5 on 2023-02-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_car_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='car-detail'),
        ),
    ]
