# Generated by Django 4.1.5 on 2023-02-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_car_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, null=True, unique=True),
        ),
    ]
