# Generated by Django 4.1.5 on 2023-02-02 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_features_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.AddField(
            model_name='car',
            name='super_CDW',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category', to='home.category'),
        ),
    ]
