# Generated by Django 4.1.5 on 2023-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_car_categories_car_super_cdw_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extras',
            field=models.ManyToManyField(blank=True, default=True, null=True, related_name='Extras', to='home.extras'),
        ),
    ]
