# Generated by Django 4.1.5 on 2023-02-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_car_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='extras',
            field=models.ManyToManyField(blank=True, null=True, related_name='Extras', to='home.extras'),
        ),
    ]
