# Generated by Django 4.1.5 on 2023-02-03 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_alter_car_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='car_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='car_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
