# Generated by Django 4.1.5 on 2023-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_car_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='time',
        ),
        migrations.AddField(
            model_name='car',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, related_name='time', to='home.time'),
        ),
    ]
