# Generated by Django 4.1.5 on 2023-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='my_date',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='end_time',
            new_name='pickup_time',
        ),
        migrations.RenameField(
            model_name='times',
            old_name='start_time',
            new_name='return_time',
        ),
        migrations.AddField(
            model_name='times',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
