# Generated by Django 4.1.5 on 2023-02-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_my_date_times_pickup_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.AlterField(
            model_name='car',
            name='time',
            field=models.ManyToManyField(blank=True, null=True, related_name='times', to='home.times'),
        ),
    ]
