# Generated by Django 4.1.5 on 2023-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_delete_time_alter_car_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
