# Generated by Django 4.1.5 on 2023-02-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_times_query_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='query_times',
        ),
    ]
