# Generated by Django 4.1.5 on 2023-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_times_query_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
