# Generated by Django 4.1.5 on 2023-02-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_times_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='duration',
        ),
    ]
