# Generated by Django 4.1.5 on 2023-02-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_times_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='time',
        ),
        migrations.AddField(
            model_name='times',
            name='total_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
    ]
