# Generated by Django 4.1.5 on 2023-02-07 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_remove_car_time_times_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='total_price',
        ),
        migrations.AddField(
            model_name='times',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
    ]
