# Generated by Django 4.1.5 on 2023-02-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_times_total_price_times_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
