# Generated by Django 4.1.5 on 2023-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_times_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='session_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
