# Generated by Django 4.1.5 on 2023-05-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
