# Generated by Django 4.1.5 on 2023-05-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_currency_api_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='api_symbol',
        ),
    ]
