# Generated by Django 4.1.5 on 2023-05-22 10:02

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_currency_api_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='do_update',
            field=django_jalali.db.models.jDateTimeField(default=False),
        ),
    ]
