# Generated by Django 4.1.5 on 2023-05-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_currency_do_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='do_update',
            field=models.BooleanField(default=False),
        ),
    ]
