# Generated by Django 4.1.5 on 2023-05-22 10:03

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_currency_do_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=django_jalali.db.models.jDateTimeField(default=False),
        ),
    ]
