# Generated by Django 4.1.5 on 2023-05-22 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_currency_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.car'),
        ),
        migrations.AlterField(
            model_name='times',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='times',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
