# Generated by Django 4.1.5 on 2023-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_times_car_alter_times_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='change',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
