# Generated by Django 4.1.5 on 2023-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_alter_times_car_alter_times_pickup_date_and_more'),
        ('order', '0004_alter_order_city_alter_order_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_services',
            field=models.ManyToManyField(blank=True, to='home.extras'),
        ),
    ]
