# Generated by Django 4.1.5 on 2023-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_extra_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_pay',
            field=models.BooleanField(default=False),
        ),
    ]
