# Generated by Django 4.1.5 on 2023-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_later_pay_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='later_pay_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='now_pay_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
    ]
