# Generated by Django 4.1.5 on 2023-06-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_full_pay_remove_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemorder',
            options={'verbose_name_plural': 'Ordered Cars'},
        ),
    ]
